# title: Bhagyalakshmi Ushakumari
# #logo: 
# theme: jekyll-theme-minimal
title: Bhagyalakshmi Ushakumari
theme: jekyll-theme-minimal
avatar: https://avatars.githubusercontent.com/u/112389695?v=4

header:
  name: Bhagyalakshmi Ushakumari
  image: https://avatars.githubusercontent.com/u/112389695?v=4  # Your GitHub profile picture

github_stats: true
github_activity_graph: true
github_top_languages: true
